export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST'
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS'
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL'


export const SUBSCRIBER_LOGIN_REQUEST = 'SUBSCRIBER_LOGIN_REQUEST'
export const SUBSCRIBER_LOGIN_SUCCESS = 'SUBSCRIBER_LOGIN_SUCCESS'
export const SUBSCRIBER_LOGIN_FAIL = 'SUBSCRIBER_LOGIN_FAIL'
export const SUBSCRIBER_LOGOUT = 'SUBSCRIBER_LOGOUT'

export const SUBSCRIBER_REGISTER_REQUEST = 'SUBSCRIBER_REGISTER_REQUEST'
export const SUBSCRIBER_REGISTER_SUCCESS = 'SUBSCRIBER_REGISTER_SUCCESS'
export const SUBSCRIBER_REGISTER_FAIL = 'SUBSCRIBER_REGISTER_FAIL'

export const SUBSCRIBER_VERIFY_REQUEST = 'SUBSCRIBER_VERIFY_REQUEST'
export const SUBSCRIBER_VERIFY_SUCCESS = 'SUBSCRIBER_VERIFY_SUCCESS'
export const SUBSCRIBER_VERIFY_FAIL = 'SUBSCRIBER_VERIFY_FAIL'


export const AUTHOR_LOGIN_REQUEST = 'AUTHOR_LOGIN_REQUEST'
export const AUTHOR_LOGIN_SUCCESS = 'AUTHOR_LOGIN_SUCCESS'
export const AUTHOR_LOGIN_FAIL = 'AUTHOR_LOGIN_FAIL'
export const AUTHOR_LOGOUT = 'AUTHOR_LOGOUT'

export const AUTHOR_REGISTER_REQUEST = 'AUTHOR_REGISTER_REQUEST'
export const AUTHOR_REGISTER_SUCCESS = 'AUTHOR_REGISTER_SUCCESS'
export const AUTHOR_REGISTER_FAIL = 'AUTHOR_REGISTER_FAIL'

export const AUTHOR_VERIFY_REQUEST = 'AUTHOR_VERIFY_REQUEST'
export const AUTHOR_VERIFY_SUCCESS = 'AUTHOR_VERIFY_SUCCESS'
export const AUTHOR_VERIFY_FAIL = 'AUTHOR_VERIFY_FAIL'

export const SET_COURSE_ID = 'SET_COURSE_ID'